# Generated by Django 5.0.6 on 2024-06-18 15:50
from typing import ClassVar

from django.db import migrations


def create_user(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("authentication", "0001_initial"),
    ]

    operations: ClassVar[list] = [migrations.RunPython(create_user)]
