# Generated by Django 5.2.5 on 2025-09-09 06:43

from django.db import migrations, models


def convert_dashboard_permission(apps, schema_editor):
    User = apps.get_model("authentication", "User")
    User.objects.filter(groups__name="Dashboard access").update(has_dashboard_access=True)


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_dashboard_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_dashboard_access",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(convert_dashboard_permission),
    ]
