# Generated by Django 5.2.10 on 2026-01-29 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_lowercase_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_dashboard_access",
        ),
    ]
