# Generated by Django 5.0.6 on 2024-06-18 15:50

from django.db import migrations
from django.utils.crypto import get_random_string

from consultation_analyser.authentication.models import User
from consultation_analyser.hosting_environment import HostingEnvironment


def create_user(apps, schema_editor):
    password = get_random_string(length=32)
    if not HostingEnvironment.is_test():
        # Don't pollute the database in the test environment
        User.objects.create_user(
            email="duncan.brown@cabinetoffice.gov.uk",
            password=password,
            is_staff=True,
            idempotent=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_user)]
