# Generated by Django 5.2.5 on 2025-09-09 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_user_has_dashboard_access"),
    ]

    operations = []
