# Generated by Django 5.0.4 on 2024-05-07 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0005_consultationresponse_submitted_at"),
        (
            "consultations",
            "0005_rename_multiple_choice_responses_answer_multiple_choice",
        ),
    ]

    operations = []
