# Generated by Django 5.0.4 on 2024-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0006_merge_20240507_1602"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="theme",
            name="unique_up_to_question",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="label",
        ),
        migrations.AddField(
            model_name="theme",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="theme",
            name="is_outlier",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="theme",
            name="keywords",
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("keywords", "question"), name="unique_up_to_question"
            ),
        ),
    ]
