# Generated by Django 5.0.6 on 2024-05-20 15:15

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        (
            "consultations",
            "0008_alter_answer_free_text_alter_answer_multiple_choice_and_more",
        ),
        ("consultations", "0008_consultation_unique_consultation_slug"),
    ]

    operations: ClassVar[list] = []
