# Generated by Django 5.0.6 on 2024-05-31 15:04
# Delete existing Themes to avoid problems with complex field changes.

from django.db import migrations


def delete_all_themes(apps, schema_editor):
    Theme = apps.get_model("consultations", "Theme")
    Theme.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0010_delete_frontend_switch"),
    ]

    operations = [
        migrations.RunPython(
            delete_all_themes, reverse_code=migrations.RunPython.noop, elidable=True
        )
    ]
