# Generated by Django 5.0.6 on 2024-05-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0012_remove_theme_unique_up_to_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="is_outlier",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Q(("theme_number", -1)),
                output_field=models.BooleanField(),
            ),
        ),
    ]
