# Generated by Django 5.0.6 on 2024-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0013_theme_is_outlier"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="theme",
            name="unique_up_to_question",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="theme_number",
            new_name="topic_id",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="keywords",
            new_name="topic_keywords",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="is_outlier",
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("topic_id", "question"), name="unique_up_to_question"
            ),
        ),
    ]
