# Generated by Django 5.0.6 on 2024-07-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "consultations",
            "0017_rename_theme_oldtheme_rename_theme_answer_old_theme_squashed_0021_remove_answer_old_theme_delete_oldtheme",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.CharField(),
        ),
    ]
