# Generated by Django 5.0.6 on 2024-07-04 22:44

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0022_alter_question_slug"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="topicmodelmetadata",
            name="scatter_plot_data",
            field=models.JSONField(default=dict),
        ),
    ]
