# Generated by Django 5.1.4 on 2025-01-06 10:29

from typing import ClassVar

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0028_rename_answer_answerold_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.RenameModel(
            old_name="Answer2",
            new_name="Answer",
        ),
        migrations.RenameModel(
            old_name="Consultation2",
            new_name="Consultation",
        ),
        migrations.RenameModel(
            old_name="Question2",
            new_name="Question",
        ),
        migrations.RenameModel(
            old_name="Theme2",
            new_name="Theme",
        ),
    ]
