# Generated by Django 5.1.4 on 2025-01-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0032_remove_sentimentmapping_answer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalexecutionrun",
            name="history_user",
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["number"]},
        ),
        migrations.AlterModelOptions(
            name="questionpart",
            options={"ordering": ["number"]},
        ),
        migrations.RemoveConstraint(
            model_name="question",
            name="unique_q_slug",
        ),
        migrations.RemoveField(
            model_name="question",
            name="order",
        ),
        migrations.RemoveField(
            model_name="questionpart",
            name="order",
        ),
        migrations.AddField(
            model_name="question",
            name="number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="questionpart",
            name="number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="questionpart",
            name="options",
            field=models.JSONField(null=True),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("consultation", "slug"), name="unique_q_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("consultation", "number"), name="unique_q_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionpart",
            constraint=models.UniqueConstraint(
                fields=("question", "number"), name="unique_part_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionpart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "free_text")),
                fields=("question",),
                name="unique_free_text_per_question",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalExecutionRun",
        ),
    ]
