# Generated by Django 5.1.4 on 2025-01-27 09:20

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0035_historicalthememapping_stance_thememapping_stance"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="historicalthememapping",
            name="stance",
            field=models.CharField(
                choices=[("POSITIVE", "Positive"), ("NEGATIVE", "Negative")],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="thememapping",
            name="stance",
            field=models.CharField(
                choices=[("POSITIVE", "Positive"), ("NEGATIVE", "Negative")],
                max_length=8,
            ),
        ),
    ]
