# Generated by Django 5.1.5 on 2025-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0038_historicalanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="key",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("framework", "key"), name="unique_framework_key"
            ),
        ),
    ]
