# Generated by Django 5.1.5 on 2025-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0039_theme_key_theme_unique_framework_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalthememapping",
            name="user_audited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="thememapping",
            name="user_audited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_theme_mapping_audited",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="is_theme_mapping_audited",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
