# Generated by Django 5.1.8 on 2025-04-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0045_thememapping_unique_theme_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="respondent",
            name="user_provided_id",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="theme",
            name="key",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
