# Generated by Django 5.1.8 on 2025-04-14 13:59

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0046_respondent_user_provided_id_alter_theme_key"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="historicalthememapping",
            name="stance",
            field=models.CharField(
                choices=[("POSITIVE", "Positive"), ("NEGATIVE", "Negative")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="thememapping",
            name="stance",
            field=models.CharField(
                choices=[("POSITIVE", "Positive"), ("NEGATIVE", "Negative")],
                max_length=8,
                null=True,
            ),
        ),
    ]
