# Generated by Django 5.2.2 on 2025-06-10 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0048_alter_executionrun_type_evidencerichmapping_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Consultation",
            new_name="ConsultationOld",
        ),
        migrations.RenameModel(
            old_name="Question",
            new_name="QuestionOld",
        ),
        migrations.RenameModel(
            old_name="Respondent",
            new_name="RespondentOld",
        ),
        migrations.RenameModel(
            old_name="Theme",
            new_name="ThemeOld",
        ),
    ]
