# Generated by Django 5.2.2 on 2025-06-11 12:14

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0049_rename_consultation_consultationold_and_more"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="questionold",
            name="consultation",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.consultationold",
            ),
        ),
        migrations.AlterField(
            model_name="respondentold",
            name="consultation",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.consultationold",
            ),
        ),
        migrations.AddIndex(
            model_name="questionold",
            index=models.Index(fields=["consultation_id"], name="explicit_con_q"),
        ),
        migrations.AddIndex(
            model_name="respondentold",
            index=models.Index(fields=["consultation_id"], name="explicit_con_respondent"),
        ),
    ]
