# Generated by Django 5.2.3 on 2025-06-26 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0055_remove_thememapping_answer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="multiple_choice_options",
        ),
        migrations.RemoveField(
            model_name="response",
            name="chosen_options",
        ),
    ]
