# Generated by Django 5.2.3 on 2025-06-26 14:23

from typing import ClassVar

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0056_remove_question_multiple_choice_options_and_more"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="question",
            name="multiple_choice_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=None, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="chosen_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=None, null=True, size=None
            ),
        ),
    ]
