# Generated by Django 5.2.3 on 2025-07-03 08:41

from typing import ClassVar

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0057_question_multiple_choice_options_and_more"),
    ]

    operations: ClassVar[list] = [
        VectorExtension(),
        migrations.AddField(
            model_name="response",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
