# Generated by Django 5.2.4 on 2025-07-07 08:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0058_response_embedding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="response",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="response",
            name="consultatio_questio_481645_idx",
        ),
        migrations.RemoveIndex(
            model_name="response",
            name="consultatio_respond_97bc2e_idx",
        ),
        migrations.AlterField(
            model_name="question",
            name="multiple_choice_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=None,
                null=True,
                size=None,
            ),
        ),
    ]
