# Generated by Django 5.2.4 on 2025-07-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0060_response_search_vector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="total_responses",
            field=models.IntegerField(
                default=0, help_text="Number of free text responses for this question"
            ),
        ),
    ]
