# Generated by Django 5.2.4 on 2025-07-28 15:24

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0062_alter_question_total_responses"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="response",
            name="free_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
