# Generated by Django 5.2.5 on 2025-08-18 12:25

from django.db import migrations, models


def populate_new_evidence_rich(apps, schema_editor):
    ResponseAnnotation = apps.get_model("consultations", "ResponseAnnotation")
    ResponseAnnotation.objects.filter(evidence_rich="YES").update(new_evidence_rich=True)
    ResponseAnnotation.objects.filter(evidence_rich="NO").update(new_evidence_rich=False)


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0066_crosscuttingtheme_theme_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="responseannotation",
            name="new_evidence_rich",
            field=models.BooleanField(default=False, blank=True, null=True),
        ),
        migrations.RunPython(populate_new_evidence_rich, reverse_code=migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="responseannotation",
            name="consultatio_evidenc_43c687_idx",
        ),
        migrations.RemoveField(
            model_name="responseannotation",
            name="evidence_rich",
        ),
        migrations.RenameField(
            model_name="responseannotation",
            old_name="new_evidence_rich",
            new_name="evidence_rich",
        ),
        migrations.AddIndex(
            model_name="responseannotation",
            index=models.Index(fields=["evidence_rich"], name="consultatio_evidenc_43c687_idx"),
        ),
    ]
