# Generated by Django 5.2.5 on 2025-09-10 14:59

from django.conf import settings
from django.db import migrations, models


def remove_human_assigned_themes(apps, schema_editor):
    ResponseAnnotationTheme = apps.get_model("consultations", "ResponseAnnotationTheme")
    ResponseAnnotationTheme.objects.exclude(assigned_by__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "consultations",
            "0072_remove_responseannotationtheme_unique_theme_assignment_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_human_assigned_themes),
        migrations.RemoveConstraint(
            model_name="responseannotationtheme",
            name="unique_theme_assignment",
        ),
        migrations.AddConstraint(
            model_name="responseannotationtheme",
            constraint=models.UniqueConstraint(
                fields=("response_annotation", "theme"), name="unique_theme_assignment"
            ),
        ),
    ]
