# Generated by Django 5.2.6 on 2025-09-23 12:53

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        (
            "consultations",
            "0073_remove_responseannotationtheme_unique_theme_assignment_and_more",
        ),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="respondent",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
