# Generated by Django 5.2.6 on 2025-09-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0074_respondent_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respondent",
            name="consultation",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.consultation",
            ),
        ),
        migrations.AlterField(
            model_name="respondent",
            name="themefinder_id",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
