# Generated by Django 5.2.6 on 2025-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0077_consultation_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="theme_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("confirmed", "Confirmed")],
                default="confirmed",
                max_length=32,
            ),
        ),
    ]
