# Generated by Django 5.2.6 on 2025-10-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0078_question_theme_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="s3_bucket",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
