# Generated by Django 5.2.6 on 2025-10-13 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0080_rename_theme_selectedtheme_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="selectedtheme",
            old_name="parent",
            new_name="crosscuttingtheme",
        ),
        migrations.AddField(
            model_name="candidatetheme",
            name="selectedtheme",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="consultations.selectedtheme",
            ),
        ),
        migrations.AddField(
            model_name="selectedtheme",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="selectedtheme",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="selectedtheme",
            name="name",
            field=models.TextField(),
        ),
    ]
