# Generated by Django 5.2.6 on 2025-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "consultations",
            "0081_rename_parent_selectedtheme_crosscuttingtheme_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatetheme",
            name="approximate_frequency",
            field=models.IntegerField(null=True),
        ),
    ]
