# Generated by Django 5.2.6 on 2025-10-21 09:46

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0082_candidatetheme_approximate_frequency"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="candidatetheme",
            name="approximate_frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
