# Generated by Django 5.2.7 on 2025-10-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0083_alter_candidatetheme_approximate_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="code",
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
