# Generated by Django 5.2.7 on 2025-10-22 10:49

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0084_consultation_code"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterField(
            model_name="consultation",
            name="code",
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
