# Generated by Django 5.2.8 on 2025-12-01 14:28

from typing import ClassVar

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0090_responsereadrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="response",
            name="read_by",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="ResponseReadRecord",
        ),
    ]
