# Generated by Django 5.2.10 on 2026-02-03 10:15

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0091_response_read_by_delete_responsereadrecord"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="consultation",
            name="display_ai_selected_themes",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="does a user see the AI selected themes in the evaluations page?",
                null=True,
            ),
        ),
    ]
