# Generated by Django 5.2.10 on 2026-02-04 07:31

import django.db.models.deletion
from django.db import migrations, models


def back_populate_responses(apps, schema_editor):
    HistoricalResponseAnnotationTheme = apps.get_model("consultations", "HistoricalResponseAnnotationTheme")
    ResponseAnnotationTheme = apps.get_model("consultations", "ResponseAnnotationTheme")

    for item in HistoricalResponseAnnotationTheme.objects.all():
        item.response = item.response_annotation.response
        item.save()

    for item in ResponseAnnotationTheme.objects.all():
        item.response = item.response_annotation.response
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0092_consultation_display_ai_selected_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresponseannotationtheme",
            name="response",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="consultations.response",
            ),
        ),
        migrations.AddField(
            model_name="responseannotationtheme",
            name="response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.response",
            ),
        ),
        migrations.RunPython(back_populate_responses),
    ]
