# Generated by Django 5.2.10 on 2026-02-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0092_consultation_display_ai_selected_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="model_name",
            field=models.CharField(
                blank=True,
                choices=[("gpt-4o-sweden", "Gpt 4O"), ("gpt-4.1", "Gpt 41")],
                default="gpt-4.1",
                help_text="llm to use",
                null=True,
            ),
        ),
    ]
