# Generated by Django 5.2.10 on 2026-02-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0093_consultation_model_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="respondent",
            name="old_demographics",
        ),
    ]
