# Generated by Django 6.0.2 on 2026-03-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0093_consultation_model_name'),
    ]

    operations = [
        # Add indexes to optimize the COUNT queries in get_queryset
        # These indexes speed up filtering responses by question and free_text conditions
        migrations.AddIndex(
            model_name='response',
            index=models.Index(
                fields=['question', 'free_text'],
                name='response_question_freetext_idx',
                condition=models.Q(free_text__isnull=False),
            ),
        ),
        # Add index for annotation lookups (used in proportion_of_audited_answers)
        migrations.AddIndex(
            model_name='responseannotation',
            index=models.Index(
                fields=['response', 'human_reviewed'],
                name='response_ann_resp_reviewed_idx',
            ),
        ),
    ]
