# Generated by Django 5.2.10 on 2026-02-04 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0094_rename_themes_responseannotation_old_themes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="responseannotationtheme",
            name="unique_theme_assignment",
        ),
        migrations.AddConstraint(
            model_name="responseannotationtheme",
            constraint=models.UniqueConstraint(
                fields=("response", "theme"), name="unique_theme_assignment"
            ),
        ),
    ]
