# Generated by Django 6.0.2 on 2026-03-26 09:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0094_remove_crosscuttingtheme_unique_cross_cutting_theme_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("s3_key", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="response",
            name="unique_question_response",
        ),
        migrations.AddField(
            model_name="question",
            name="closed_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="consultations.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="identifier",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("demographic", "Demographic"), ("closed", "Closed"), ("open", "Open")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="stage",
            field=models.CharField(
                choices=[
                    ("setup", "Data Setup"),
                    ("finding_themes", "Finding Themes"),
                    ("finalising_themes", "Finalising Themes"),
                    ("assigning_themes", "Assigning Themes"),
                    ("analysis", "Analysis"),
                    ("theme_sign_off", "Theme Sign Off"),
                    ("theme_mapping", "Theme Mapping"),
                ],
                default="theme_sign_off",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="theme_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("configured", "Configured"),
                    ("finalising_themes", "Finalising Themes"),
                    ("confirmed", "Confirmed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="consultation",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.consultation",
            ),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
