# Generated by Django 5.2.10 on 2026-02-04 11:13

import uuid

import django.db.models.deletion
import pgvector.django.vector
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0094_historicalresponseannotationtheme_response_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("free_text", models.TextField(blank=True, null=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical response",
                "verbose_name_plural": "historical responses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name="responseannotationtheme",
            name="unique_theme_assignment",
        ),
        migrations.RenameField(
            model_name="historicalresponseannotationtheme",
            old_name="response_annotation",
            new_name="old_response_annotation",
        ),
        migrations.RenameField(
            model_name="responseannotation",
            old_name="themes",
            new_name="old_themes",
        ),
        migrations.RemoveField(
            model_name="responseannotationtheme",
            name="response_annotation",
        ),
        migrations.AddField(
            model_name="response",
            name="themes",
            field=models.ManyToManyField(
                blank=True,
                through="consultations.ResponseAnnotationTheme",
                to="consultations.selectedtheme",
            ),
        ),
        migrations.AddField(
            model_name="responseannotationtheme",
            name="old_response_annotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.responseannotation",
            ),
        ),
        migrations.AlterField(
            model_name="responseannotationtheme",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="consultations.response"
            ),
        ),
        migrations.AddConstraint(
            model_name="responseannotationtheme",
            constraint=models.UniqueConstraint(
                fields=("response", "theme"), name="unique_theme_assignment"
            ),
        ),
        migrations.AddField(
            model_name="historicalresponse",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalresponse",
            name="question",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="consultations.question",
            ),
        ),
        migrations.AddField(
            model_name="historicalresponse",
            name="respondent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="consultations.respondent",
            ),
        ),
    ]
