# Generated by Django 6.0.2 on 2026-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0095_add_reviewed_responses_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multichoiceanswer',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='multichoiceanswer',
            index=models.Index(fields=['question'], name='consultatio_questio_faff68_idx'),
        ),
    ]
