# Generated by Django 5.2.10 on 2026-02-05 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def back_populate_responses(apps, schema_editor):
    HistoricalResponseAnnotation = apps.get_model("consultations", "HistoricalResponseAnnotation")
    ResponseAnnotation = apps.get_model("consultations", "ResponseAnnotation")

    for item in HistoricalResponseAnnotation.objects.all():
        item.response.evidence_rich = item.evidence_rich
        item.response.human_reviewed = item.human_reviewed
        item.response.reviewed_at = item.reviewed_at
        item.response.reviewed_by = item.reviewed_by
        item.response.sentiment = item.sentiment
        item.response.save()

    for item in ResponseAnnotation.objects.all():
        item.response.evidence_rich = item.evidence_rich
        item.response.human_reviewed = item.human_reviewed
        item.response.reviewed_at = item.reviewed_at
        item.response.reviewed_by = item.reviewed_by
        item.response.sentiment = item.sentiment
        item.response.save()


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0095_historicalresponse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalresponse",
            name="evidence_rich",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalresponse",
            name="human_reviewed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalresponse",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalresponse",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalresponse",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGREEMENT", "Agreement"),
                    ("DISAGREEMENT", "Disagreement"),
                    ("UNCLEAR", "Unclear"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="evidence_rich",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="flagged_by",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="human_reviewed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGREEMENT", "Agreement"),
                    ("DISAGREEMENT", "Disagreement"),
                    ("UNCLEAR", "Unclear"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(fields=["human_reviewed"], name="consultatio_human_r_53734f_idx"),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(fields=["sentiment"], name="consultatio_sentime_450fc3_idx"),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(fields=["evidence_rich"], name="consultatio_evidenc_fc8cbd_idx"),
        ),
        migrations.RunPython(back_populate_responses),
    ]
