# Generated by Django 6.0.2 on 2026-03-27 13:16

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("consultations", "0095_fileupload_remove_response_unique_question_response_and_more"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("configured", "Configured"),
                    ("finalising_themes", "Finalising Themes"),
                    ("confirmed", "Confirmed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
    ]
