# Generated by Django 5.2.10 on 2026-02-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0095_remove_responseannotationtheme_unique_theme_assignment_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalresponse",
            name="search_vector",
        ),
    ]
