# Generated by Django 5.2.10 on 2026-02-06 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0096_historicalresponse_evidence_rich_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="responseannotation",
            name="flagged_by",
        ),
        migrations.RemoveField(
            model_name="responseannotation",
            name="old_themes",
        ),
        migrations.RemoveField(
            model_name="responseannotation",
            name="response",
        ),
        migrations.RemoveField(
            model_name="responseannotation",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="responseannotationtheme",
            name="old_response_annotation",
        ),
        migrations.RemoveField(
            model_name="historicalresponseannotationtheme",
            name="old_response_annotation",
        ),
        migrations.AlterField(
            model_name="response",
            name="flagged_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="flagged_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalResponseAnnotation",
        ),
        migrations.DeleteModel(
            name="ResponseAnnotation",
        ),
    ]
