# Generated by Django 6.0.2 on 2026-04-02 11:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0096_question_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateThemeResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultations.candidatetheme",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="consultations.response"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["candidate_theme"], name="consultatio_candida_13d7bd_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate_theme", "response"),
                        name="unique_candidate_theme_response",
                    )
                ],
            },
        ),
    ]
