# Generated by Django 6.0.2 on 2026-03-18 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0096_question_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='response',
            index=models.Index(condition=models.Q(('free_text__isnull', False), models.Q(('free_text', ''), _negated=True)), fields=['question'], name='resp_q_has_ft_idx'),
        ),
        migrations.AddIndex(
            model_name='responseannotation',
            index=models.Index(fields=['response', 'human_reviewed'], name='resp_ann_resp_rev_idx'),
        ),
    ]
