# Generated by Django 6.0.2 on 2026-04-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0097_candidatethemeresponse'),
    ]

    operations = [
        # Add indexes to Response model
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['question'], name='response_question_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['respondent'], name='response_respondent_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['question', 'respondent'], name='response_q_r_idx'),
        ),
        
        # Add indexes to ResponseAnnotation model
        migrations.AddIndex(
            model_name='responseannotation',
            index=models.Index(fields=['response'], name='annotation_response_idx'),
        ),
        migrations.AddIndex(
            model_name='responseannotation',
            index=models.Index(fields=['sentiment', 'evidence_rich'], name='annotation_filter_idx'),
        ),
        
        # Add indexes to ResponseAnnotationTheme model
        migrations.AddIndex(
            model_name='responseannotationtheme',
            index=models.Index(fields=['response_annotation'], name='rat_annotation_idx'),
        ),
        migrations.AddIndex(
            model_name='responseannotationtheme',
            index=models.Index(fields=['theme'], name='rat_theme_idx'),
        ),
        migrations.AddIndex(
            model_name='responseannotationtheme',
            index=models.Index(fields=['response_annotation', 'theme'], name='rat_ann_theme_idx'),
        ),
        migrations.AddIndex(
            model_name='responseannotationtheme',
            index=models.Index(fields=['assigned_by'], name='rat_assigned_by_idx'),
        ),
    ]
