# Generated by Django 6.0.2 on 2026-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0097_candidatethemeresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographicoption",
            name="field_name",
            field=models.CharField(max_length=512),
        ),
    ]
