# Generated by Django 6.0.2 on 2026-03-18 09:56

from django.db import migrations, models


def populate_reviewed_responses_count(apps, schema_editor):
    """Populate the reviewed_responses_count field for existing questions"""
    Question = apps.get_model('consultations', 'Question')
    Response = apps.get_model('consultations', 'Response')

    questions = Question.objects.filter(has_free_text=True)
    total = questions.count()

    print(f"\nPopulating reviewed_responses_count for {total} questions with free text...")

    for i, question in enumerate(questions, 1):
        # Count human-reviewed responses for this question
        count = Response.objects.filter(
            question=question,
            free_text__isnull=False,
            annotation__human_reviewed=True
        ).exclude(free_text='').count()

        question.reviewed_responses_count = count
        question.save(update_fields=['reviewed_responses_count'])

        if i % 10 == 0 or i == total:
            print(f"  Progress: {i}/{total} questions ({i/total*100:.1f}%)")

    print(f"✓ Completed populating reviewed_responses_count for {total} questions")


def reverse_populate(apps, schema_editor):
    """No need to reverse - the field will be dropped on rollback"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0097_response_resp_q_has_ft_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reviewed_responses_count',
            field=models.IntegerField(
                default=0,
                help_text='Denormalized count of human-reviewed responses for performance'
            ),
        ),
        migrations.RunPython(populate_reviewed_responses_count, reverse_populate),
    ]
