# Generated by Django 6.0.2 on 2026-03-19 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0099_alter_multichoiceanswer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['question', 'respondent'], name='consultatio_questio_4b7560_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['respondent'], name='consultatio_respond_e5563f_idx'),
        ),
        migrations.AddIndex(
            model_name='responseannotationtheme',
            index=models.Index(fields=['response_annotation', 'theme'], name='consultatio_respons_204566_idx'),
        ),
        migrations.AddIndex(
            model_name='responseannotationtheme',
            index=models.Index(fields=['theme'], name='consultatio_theme_i_32e67d_idx'),
        ),
        migrations.AddIndex(
            model_name='responseannotationtheme',
            index=models.Index(fields=['assigned_by'], name='consultatio_assigne_4234d9_idx'),
        ),
    ]
