# Generated by Django 6.0.2 on 2026-05-28 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0100_remove_legacy_stage_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['question', 'id'], name='consultatio_questio_13c9db_idx'),
        ),
    ]
