# Generated by Django 6.0.6 on 2026-07-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0103_add_response_question_id_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="stage",
            field=models.CharField(
                choices=[
                    ("setup", "Data Setup"),
                    ("finding_themes", "Finding Themes"),
                    ("finalising_themes", "Finalising Themes"),
                    ("assigning_themes", "Assigning Themes"),
                    ("analysis", "Analysis"),
                ],
                default="setup",
                max_length=32,
            ),
        ),
    ]
