# Generated by Django 6.1 on 2026-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0104_alter_consultation_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='assign_themes_running',
            field=models.BooleanField(default=False),
        ),
    ]
