# Generated by Django 6.1 on 2026-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0104_alter_consultation_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='running_job',
            field=models.CharField(choices=[('find-themes', 'Find Themes'), ('assign-themes', 'Assign Themes')], default=None, max_length=16, null=True),
        ),
    ]
