# Generated by Django 6.1 on 2026-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0105_consultation_running_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='data_source',
            field=models.CharField(choices=[('qualtrics', 'Qualtrics'), ('citizen-space', 'Citizen Space')], default=None, max_length=128, null=True),
        ),
    ]
