# Generated by Django 6.1 on 2026-09-21 18:46
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("consultations", "0106_consultation_data_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="consultation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this consultation (owner).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_consultations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
