# Generated by Django 6.1 on 2026-09-22 13:21

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ('consultations', '0106_consultation_data_source'),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name='consultation',
            name='running_job',
            field=models.CharField(choices=[('find-themes', 'Find Themes'), ('assign-themes', 'Assign Themes'), ('delete-consultation', 'Delete Consultation')], default=None, max_length=32, null=True),
        ),
    ]
