# Generated by Django 6.1 on 2026-09-23 12:53

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):

    dependencies: ClassVar = [
        ('consultations', '0107_consultation_created_by'),
        ('consultations', '0108_alter_consultation_running_job'),
    ]

    operations: ClassVar = [
    ]
