# Generated by Django 6.1 on 2026-09-28 10:10

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("consultations", "0109_merge_20260923_1353"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="consultation",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the consultation closed to responses.", null=True
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="When the consultation opened to responses.", null=True
            ),
        ),
    ]
