"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

import environ
from i_dot_ai_utilities.logging.structured_logger import StructuredLogger
from i_dot_ai_utilities.logging.types.enrichment_types import ExecutionEnvironmentType
from i_dot_ai_utilities.logging.types.log_output_format import LogOutputFormat

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=False)

env = environ.Env(DEBUG=(bool, False))

SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = env("DEBUG")
ENVIRONMENT = env("ENVIRONMENT")

DOMAIN_NAME = env("DOMAIN_NAME", default="0.0.0.0")  # nosec

ALLOWED_HOSTS: list[str] = [DOMAIN_NAME, "*"]  # nosec

# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.auth",
    "django.contrib.admin",
    "backend.authentication",
    "backend.consultations",
    "backend.ingest",
    "crispy_forms",
    "crispy_forms_gds",
    "django.contrib.humanize",
    "django_rq",
    "simple_history",
    "rest_framework",
    "django_filters",
    "rest_framework_simplejwt",
    "drf_spectacular",
]


# TODO: steal code from this blog post to add a health check endpoint: https://testdriven.io/blog/deploying-django-to-ecs-with-terraform/#django-health-check

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "backend.middleware.JWTAuthenticationMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.common.CommonMiddleware",
    "backend.middleware.CSRFExemptMiddleware",  # Must be before CsrfViewMiddleware
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "backend.middleware.SupportAppStaffRequiredMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "DIRS": [],
        "OPTIONS": {
            "context_processors": [
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ]
        },
    },
]

WSGI_APPLICATION = "wsgi.application"

AUTH_USER_MODEL = "authentication.User"

# Local and testing origin
TRUSTED_ORIGIN = "http://localhost:3000"

if ENVIRONMENT.lower() == "prod":
    TRUSTED_ORIGIN = "https://consult.ai.cabinetoffice.gov.uk"
if ENVIRONMENT.lower() == "dev":
    TRUSTED_ORIGIN = "https://consult-dev.ai.cabinetoffice.gov.uk"
if ENVIRONMENT.lower() == "preprod":
    TRUSTED_ORIGIN = "https://consult-preprod.ai.cabinetoffice.gov.uk"

CSRF_TRUSTED_ORIGINS = [TRUSTED_ORIGIN]

# Database with Connection Pooling
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

_db_config = env.db()
DATABASES = {
    "default": {
        **_db_config,
        # Use django-db-connection-pool backend for PostgreSQL
        "ENGINE": "dj_db_conn_pool.backends.postgresql",
        # Connection pooling settings
        "POOL_OPTIONS": {
            "INITIAL_CONNS": env.int("DB_POOL_INITIAL_CONNS", default=5),
            "MAX_CONNS": env.int("DB_POOL_MAX_CONNS", default=20),
            "MIN_CONNS": env.int("DB_POOL_MIN_CONNS", default=5),
            "MAX_SHARED_CONNS": env.int("DB_POOL_MAX_SHARED_CONNS", default=10),
            "MAX_OVERFLOW": env.int("DB_POOL_MAX_OVERFLOW", default=10),
            "RECYCLE": env.int("DB_POOL_RECYCLE", default=3600),  # 1 hour
            "PRE_PING": env.bool("DB_POOL_PRE_PING", default=True),
        },
        # Keep existing options
        "OPTIONS": {
            **_db_config.get("OPTIONS", {}),
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "pipeline": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {name}: {message}",
            "style": "{",
        },
        "rq_console": {
            "format": "%(asctime)s %(message)s",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "stdout": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "pipeline",
        },
        "rq_console": {
            "level": "INFO",
            "class": "rq.logutils.ColorizingStreamHandler",
            "stream": sys.stdout,
            "formatter": "rq_console",
            "exclude": ["%(asctime)s"],
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "sql.log",
        },
    },
    "loggers": {
        "pipeline": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "upload": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "import": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "export": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "dummy_data": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "rq.worker": {"handlers": ["rq_console"], "level": "INFO"},
        "django.db.backends": {"handlers": ["file"], "level": "DEBUG", "propagate": False},
    },
}


LOGGER = StructuredLogger(
    level="info",
    options={
        "execution_environment": ExecutionEnvironmentType.LOCAL,
        "log_format": LogOutputFormat.JSON,
    },
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django URL format
APPEND_SLASH = True

# Crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "gds"
CRISPY_TEMPLATE_PACK = "gds"

# AWS variables
BATCH_JOB_QUEUE = env("BATCH_JOB_QUEUE", default=None)
BATCH_JOB_DEFINITION = env("BATCH_JOB_DEFINITION", default=None)
AWS_REGION = env("AWS_REGION")
AWS_BUCKET_NAME = env("AWS_BUCKET_NAME")

ASSIGN_THEMES_BATCH_JOB_NAME = env("ASSIGN_THEMES_BATCH_JOB_NAME")
ASSIGN_THEMES_BATCH_JOB_QUEUE = env("ASSIGN_THEMES_BATCH_JOB_QUEUE")
ASSIGN_THEMES_BATCH_JOB_DEFINITION = env("ASSIGN_THEMES_BATCH_JOB_DEFINITION")
FIND_THEMES_BATCH_JOB_NAME = env("FIND_THEMES_BATCH_JOB_NAME")
FIND_THEMES_BATCH_JOB_QUEUE = env("FIND_THEMES_BATCH_JOB_QUEUE")
FIND_THEMES_BATCH_JOB_DEFINITION = env("FIND_THEMES_BATCH_JOB_DEFINITION")


# version info
GIT_SHA = env("GIT_SHA", default=None)

# redis
redis_host = env.str("REDIS_HOST", "localhost")
redis_port = env.str("REDIS_PORT", "6379")
redis_url = f"redis://{redis_host}:{redis_port}"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "redis": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": redis_url,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "MAX_ENTRIES": 5000,
        },
    },
}

# rq
RQ_QUEUES = {
    "default": {
        "USE_REDIS_CACHE": "redis",
        "ASYNC": True,
    },
}

if DEBUG:
    INTERNAL_IPS = ["127.0.0.1"]

# changing this will require a database migration
EMBEDDING_DIMENSION = 3072

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_RENDERER_CLASSES": (
        "drf_orjson_renderer.renderers.ORJSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=18),
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Consultation Analyser API",
    "DESCRIPTION": "REST API for the i.AI Consultation Analyser platform",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
}

AUTH_API_URL = env.str("AUTH_API_URL", None)
