# Generated by Django 5.0.3 on 2024-03-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationresponse",
            name="consultation",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="consultations.consultation"
            ),
        ),
    ]
