# Generated by Django 5.0.2 on 2024-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="slug",
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
