# Generated by Django 5.0.3 on 2024-03-26 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theme",
            options={},
        ),
        migrations.AddField(
            model_name="theme",
            name="question",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="consultations.question"
            ),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("summary", "label", "keywords", "question"), name="unique_up_to_question"
            ),
        ),
    ]
