# Generated by Django 5.0.3 on 2024-03-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('slug', 'section'), name='unique_question_section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('slug', 'consultation'), name='unique_section_consultation'),
        ),
    ]
