# Generated by Django 5.0.3 on 2024-03-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_question_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('organisation_identifier', models.CharField(blank=True, choices=[('dept-for-education', 'Department for Education'), ('cabinet-office', 'Cabinet Office')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, max_length=256)),
                ('location', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=256)),
                ('summary', models.TextField(blank=True)),
                ('keywords', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='closed_response_options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.consultation'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_response', models.CharField(blank=True, max_length=256)),
                ('free_text_response', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.question')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.respondent')),
                ('theme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='consultations.theme')),
            ],
        ),
    ]
