# Generated by Django 5.0.3 on 2024-03-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0002_consultationresponse_consultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="question",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="consultations.question"
            ),
        ),
    ]
