# Generated by Django 5.0.4 on 2024-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0002_alter_theme_options_theme_question_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="theme",
            name="unique_up_to_question",
        ),
        migrations.AddField(
            model_name="theme",
            name="is_outlier",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(fields=("label", "question"), name="unique_up_to_question"),
        ),
    ]
