# Generated by Django 5.0.4 on 2024-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "consultations",
            "0003_remove_theme_unique_up_to_question_theme_is_outlier_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="is_outlier",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="theme",
            name="keywords",
            field=models.JSONField(default=list, editable=False),
        ),
    ]
