# Generated by Django 5.0.4 on 2024-05-07 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0004_consultation_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="multiple_choice_responses",
            new_name="multiple_choice",
        ),
    ]
