# Generated by Django 5.0.4 on 2024-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "consultations",
            "0005_rename_multiple_choice_responses_answer_multiple_choice",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="theme",
            name="unique_up_to_question",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="label",
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(fields=("keywords", "question"), name="unique_up_to_question"),
        ),
    ]
