# Generated by Django 5.0.4 on 2024-05-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0006_remove_theme_unique_up_to_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="short_description",
            field=models.TextField(blank=True),
        ),
    ]
