# Generated by Django 5.0.4 on 2024-05-17 08:15

import django.db.models.deletion
from django.db import migrations, models

import consultation_analyser.consultations.models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0007_remove_theme_unique_up_to_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="free_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="multiple_choice",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[consultation_analyser.consultations.models.MultipleChoiceSchemaValidator(limit_value=None)],
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.theme",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="multiple_choice_options",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[consultation_analyser.consultations.models.MultipleChoiceSchemaValidator(limit_value=None)],
            ),
        ),
    ]
