# Generated by Django 5.0.4 on 2024-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0007_theme_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="is_outlier",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="theme",
            name="keywords",
            field=models.JSONField(default=list),
        ),
    ]
