# Generated by Django 5.0.6 on 2024-05-23 20:05

from django.db import migrations


def delete_switch(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")
    try:
        switch = Switch.objects.get(name="FRONTEND_USER_LOGIN")
        switch.delete()
    except Switch.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0009_merge_20240520_1515"),
        ("waffle", "0004_update_everyone_nullbooleanfield"),
    ]

    operations = [migrations.RunPython(delete_switch)]
