# Generated by Django 5.0.6 on 2024-05-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0011_delete_existing_themes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="theme",
            name="unique_up_to_question",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="is_outlier",
        ),
        migrations.AddField(
            model_name="theme",
            name="theme_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("theme_number", "question"), name="unique_up_to_question"
            ),
        ),
    ]
