# Generated by Django 5.0.6 on 2024-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0014_remove_theme_unique_up_to_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="is_outlier",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Q(("topic_id", -1)),
                output_field=models.BooleanField(),
            ),
        ),
    ]
