# Generated by Django 5.0.6 on 2024-06-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0015_theme_is_outlier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="consultations.theme",
            ),
        ),
    ]
