# Generated by Django 5.0.6 on 2024-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0016_alter_answer_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="is_no_response",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Q(("topic_id", None)),
                output_field=models.BooleanField(),
            ),
        ),
    ]
