# Generated by Django 5.0.6 on 2024-07-01 08:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("consultations", "0017_rename_theme_oldtheme_rename_theme_answer_old_theme"),
        (
            "consultations",
            "0018_theme_processingrun_answer_themes_topicmodelmetadata_and_more",
        ),
        ("consultations", "0019_alter_topicmodelmetadata_options_and_more"),
        ("consultations", "0020_theme_processing_run"),
        ("consultations", "0021_remove_answer_old_theme_delete_oldtheme"),
    ]

    dependencies = [
        ("consultations", "0016_alter_answer_theme"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Theme",
            new_name="OldTheme",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="theme",
            new_name="old_theme",
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("topic_keywords", models.JSONField(default=list)),
                ("topic_id", models.IntegerField(null=True)),
                (
                    "is_outlier",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Q(("topic_id", -1)),
                        output_field=models.BooleanField(),
                    ),
                ),
                ("short_description", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultations.consultation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="themes",
            field=models.ManyToManyField(to="consultations.theme"),
        ),
        migrations.CreateModel(
            name="TopicModelMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "processing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultations.processingrun",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultations.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="theme",
            name="topic_model_metadata",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.topicmodelmetadata",
            ),
        ),
        migrations.AddConstraint(
            model_name="topicmodelmetadata",
            constraint=models.UniqueConstraint(
                fields=("processing_run", "question"),
                name="unique_topic_model_question_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("topic_id", "topic_model_metadata"), name="unique_id_per_model"
            ),
        ),
        migrations.AlterModelOptions(
            name="topicmodelmetadata",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="topicmodelmetadata",
            name="unique_topic_model_question_run",
        ),
        migrations.RemoveField(
            model_name="topicmodelmetadata",
            name="processing_run",
        ),
        migrations.RemoveField(
            model_name="topicmodelmetadata",
            name="question",
        ),
        migrations.AddField(
            model_name="theme",
            name="processing_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.processingrun",
            ),
        ),
        migrations.RemoveField(
            model_name="answer",
            name="old_theme",
        ),
        migrations.DeleteModel(
            name="OldTheme",
        ),
    ]
