# Generated by Django 5.0.6 on 2024-06-25 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0016_alter_answer_theme"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Theme",
            new_name="OldTheme",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="theme",
            new_name="old_theme",
        ),
    ]
