# Generated by Django 5.0.6 on 2024-06-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0017_processingrun_topicmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processingrun",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="topicmodel",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="theme",
            name="topic_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.topicmodel",
            ),
        ),
    ]
