# Generated by Django 5.0.6 on 2024-06-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0017_processingrun_topicmodel_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="theme",
            name="unique_up_to_question",
        ),
        migrations.AddField(
            model_name="theme",
            name="topic_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.topicmodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("topic_id", "topic_model"), name="unique_id_per_model"
            ),
        ),
    ]
