# Generated by Django 5.0.6 on 2024-06-26 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "consultations",
            "0018_theme_processingrun_answer_themes_topicmodelmetadata_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topicmodelmetadata",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="topicmodelmetadata",
            name="unique_topic_model_question_run",
        ),
        migrations.RemoveField(
            model_name="topicmodelmetadata",
            name="processing_run",
        ),
        migrations.RemoveField(
            model_name="topicmodelmetadata",
            name="question",
        ),
    ]
