# Generated by Django 5.0.6 on 2024-06-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0019_alter_topicmodelmetadata_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="processing_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.processingrun",
            ),
        ),
    ]
