# Generated by Django 5.0.6 on 2024-06-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0019_update_existing_themes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="question",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="theme",
        ),
        migrations.AddField(
            model_name="answer",
            name="theme",
            field=models.ManyToManyField(to="consultations.theme"),
        ),
    ]
