# Generated by Django 5.0.6 on 2024-06-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0020_remove_theme_question_remove_answer_theme_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TopicModel",
            new_name="TopicModelMetadata",
        ),
        migrations.RemoveConstraint(
            model_name="theme",
            name="unique_id_per_model",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="topic_model",
            new_name="topic_model_metadata",
        ),
        migrations.AddConstraint(
            model_name="theme",
            constraint=models.UniqueConstraint(
                fields=("topic_id", "topic_model_metadata"), name="unique_id_per_model"
            ),
        ),
    ]
