# Generated by Django 5.0.6 on 2024-06-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0021_rename_topicmodel_topicmodelmetadata_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="theme",
            new_name="themes",
        ),
    ]
