# Generated by Django 5.0.7 on 2024-07-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0023_topicmodelmetadata_scatter_plot_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingrun",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
