# Generated by Django 5.0.7 on 2024-07-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0023_topicmodelmetadata_scatter_plot_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingrun",
            name="topic_model_parameters",
            field=models.JSONField(default=dict),
        ),
    ]
