# Generated by Django 5.0.7 on 2024-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0025_populate_existing_processing_run_slugs"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="processingrun",
            constraint=models.UniqueConstraint(
                fields=("slug", "consultation"), name="unique_slug_consultation"
            ),
        ),
    ]
