# Generated by Django 5.1.4 on 2025-01-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0028_alter_consultation2_slug_alter_question2_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer2",
            name="chosen_options",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="questionpart",
            name="order",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="question2",
            name="order",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="questionpart",
            name="options",
            field=models.JSONField(default=list),
        ),
    ]
