# Generated by Django 5.1.4 on 2025-01-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0029_answer2_chosen_options_questionpart_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme2",
            name="execution_run",
        ),
        migrations.AddField(
            model_name="framework",
            name="execution_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.executionrun",
            ),
        ),
    ]
