# Generated by Django 5.1.4 on 2025-01-06 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0030_alter_framework_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultationold",
            name="users",
        ),
        migrations.RemoveField(
            model_name="section",
            name="consultation",
        ),
        migrations.RemoveField(
            model_name="processingrun",
            name="consultation",
        ),
        migrations.RemoveField(
            model_name="consultationresponse",
            name="consultation",
        ),
        migrations.RemoveField(
            model_name="themeold",
            name="processing_run",
        ),
        migrations.RemoveField(
            model_name="questionold",
            name="section",
        ),
        migrations.RemoveField(
            model_name="themeold",
            name="topic_model_metadata",
        ),
        migrations.DeleteModel(
            name="AnswerOld",
        ),
        migrations.DeleteModel(
            name="ConsultationOld",
        ),
        migrations.DeleteModel(
            name="ConsultationResponse",
        ),
        migrations.DeleteModel(
            name="ProcessingRun",
        ),
        migrations.DeleteModel(
            name="QuestionOld",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="ThemeOld",
        ),
        migrations.DeleteModel(
            name="TopicModelMetadata",
        ),
    ]
