# Generated by Django 5.1.4 on 2025-01-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0034_rename_text_consultation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalthememapping",
            name="stance",
            field=models.CharField(
                choices=[("POSITIVE", "Positive"), ("NEGATIVE", "Negative")],
                default="POSITIVE",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="thememapping",
            name="stance",
            field=models.CharField(
                choices=[("POSITIVE", "Positive"), ("NEGATIVE", "Negative")],
                default="POSITIVE",
                max_length=8,
            ),
        ),
    ]
