# Generated by Django 5.1.5 on 2025-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0039_theme_key_theme_unique_framework_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalthememapping",
            name="stance",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "Positive"),
                    ("NEGATIVE", "Negative"),
                    ("HUMAN", "Human"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="thememapping",
            name="stance",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "Positive"),
                    ("NEGATIVE", "Negative"),
                    ("HUMAN", "Human"),
                ],
                max_length=8,
            ),
        ),
    ]
