# Generated by Django 5.1.6 on 2025-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0041_historicalsentimentmapping_sentimentmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="respondent",
            name="themefinder_respondent_id",
            field=models.IntegerField(null=True),
        ),
    ]
