# Generated by Django 5.1.7 on 2025-03-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0043_convert_jsonfield_data_to_json"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="thememapping",
            constraint=models.UniqueConstraint(
                fields=("answer", "theme", "execution_run"), name="unique_theme_mapping"
            ),
        ),
    ]
