# Generated by Django 5.1.7 on 2025-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0044_thememapping_unique_theme_mapping"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="thememapping",
            name="unique_theme_mapping",
        ),
        migrations.AddConstraint(
            model_name="thememapping",
            constraint=models.UniqueConstraint(
                fields=("answer", "theme"), name="unique_theme_mapping"
            ),
        ),
    ]
