# Generated by Django 5.1.7 on 2025-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0044_delete_duplicate_theme_mappings"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="thememapping",
            constraint=models.UniqueConstraint(
                fields=("answer", "theme"), name="unique_theme_answer"
            ),
        ),
    ]
