# Generated by Django 5.1.7 on 2025-04-10 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0046_respondent_user_provided_id_alter_theme_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="framework",
            old_name="execution_run",
            new_name="theme_generation_execution_run",
        ),
        migrations.RenameField(
            model_name="historicalsentimentmapping",
            old_name="execution_run",
            new_name="sentiment_analysis_execution_run",
        ),
        migrations.RenameField(
            model_name="historicalthememapping",
            old_name="execution_run",
            new_name="theme_mapping_execution_run",
        ),
        migrations.RenameField(
            model_name="sentimentmapping",
            old_name="execution_run",
            new_name="sentiment_analysis_execution_run",
        ),
        migrations.RenameField(
            model_name="thememapping",
            old_name="execution_run",
            new_name="theme_mapping_execution_run",
        ),
    ]
