# Generated by Django 5.2.2 on 2025-06-16 13:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0051_consultation_question_respondent_response_theme_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DemographicOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(max_length=128)),
                ("field_value", models.CharField(max_length=256)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="response",
            name="consultatio_free_te_47c4fc_idx",
        ),
        migrations.AddField(
            model_name="demographicoption",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.consultation",
            ),
        ),
        migrations.AddIndex(
            model_name="demographicoption",
            index=models.Index(
                fields=["consultation", "field_name"],
                name="consultatio_consult_fd8b04_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="demographicoption",
            constraint=models.UniqueConstraint(
                fields=("consultation", "field_name", "field_value"),
                name="unique_demographic_option",
            ),
        ),
    ]
