# Generated by Django 5.1.8 on 2025-06-12 15:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0051_consultation_question_respondent_response_theme_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("consultation_name", models.CharField(max_length=255)),
                ("consultation_code", models.CharField(max_length=100)),
                ("timestamp", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALIDATING", "Validating"),
                            ("IMPORTING_CONSULTATION", "Creating consultation"),
                            ("IMPORTING_RESPONDENTS", "Importing respondents"),
                            ("IMPORTING_QUESTIONS", "Importing questions"),
                            ("IMPORTING_RESPONSES", "Importing responses"),
                            ("IMPORTING_ANNOTATIONS", "Importing annotations"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                ("completed_questions", models.IntegerField(default=0)),
                ("total_responses", models.IntegerField(default=0)),
                ("completed_responses", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_records",
                        to="consultations.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["status"], name="consultatio_status_8f30ab_idx"
                    ),
                    models.Index(
                        fields=["consultation_code"],
                        name="consultatio_consult_5d32a0_idx",
                    ),
                ],
            },
        ),
    ]
