# Generated by Django 5.1.8 on 2025-06-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0052_add_consultation_import_model"),
        ("consultations", "0052_add_demographics_gin_index"),
    ]

    operations = []
