# Generated by Django 5.1.8 on 2025-06-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0052_add_demographics_gin_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="respondent",
            name="respondent_demographics_gin",
        ),
    ]
