# Generated by Django 5.1.8 on 2025-06-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0053_remove_respondent_respondent_demographics_gin"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="response",
            name="consultatio_free_te_47c4fc_idx",
        ),
    ]
