# Generated by Django 5.1.8 on 2025-06-16 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0054_remove_response_consultatio_free_te_47c4fc_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemographicOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(max_length=128)),
                ("field_value", models.CharField(max_length=256)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultations.consultation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["consultation", "field_name"],
                        name="consultatio_consult_fd8b04_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consultation", "field_name", "field_value"),
                        name="unique_demographic_option",
                    )
                ],
            },
        ),
    ]
