# Generated by Django 5.2.4 on 2025-07-07 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0058_response_embedding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="response",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="response",
            name="consultatio_questio_481645_idx",
        ),
        migrations.RemoveIndex(
            model_name="response",
            name="consultatio_respond_97bc2e_idx",
        ),
    ]
