# Generated by Django 5.2.4 on 2025-07-09 12:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0059_alter_response_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="response",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="consultatio_search__7daa4d_gin"
            ),
        ),
    ]
