# Generated by Django 5.2.4 on 2025-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0061_question_total_responses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="total_responses",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of free text responses for this question",
                null=True,
            ),
        ),
    ]
