# Generated by Django 5.2.4 on 2025-07-24 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0062_alter_question_total_responses"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossCuttingTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultations.consultation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CrossCuttingThemeAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "cross_cutting_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_assignments",
                        to="consultations.crosscuttingtheme",
                    ),
                ),
                (
                    "theme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consultations.theme",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="crosscuttingtheme",
            index=models.Index(
                fields=["consultation"], name="consultatio_consult_0f4af5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="crosscuttingtheme",
            constraint=models.UniqueConstraint(
                fields=("consultation", "name"), name="unique_cross_cutting_theme"
            ),
        ),
        migrations.AddIndex(
            model_name="crosscuttingthemeassignment",
            index=models.Index(
                fields=["cross_cutting_theme"], name="consultatio_cross_c_69304c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="crosscuttingthemeassignment",
            constraint=models.UniqueConstraint(
                fields=("theme",), name="unique_theme_to_cct_assignment"
            ),
        ),
    ]
