# Generated by Django 5.2.4 on 2025-07-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0063_alter_response_free_text"),
        (
            "consultations",
            "0063_crosscuttingtheme_crosscuttingthemeassignment_and_more",
        ),
    ]

    operations = []
