# Generated by Django 5.2.4 on 2025-08-05 10:15

import pgvector.django.vector
from django.db import migrations


def clear_embeddings(apps, schema_editor):
    """
    Clear all existing embeddings since they're incompatible with new dimensions.
    """
    Response = apps.get_model("consultations", "Response")
    Response.objects.update(embedding=None)


def reverse_regenerate(apps, schema_editor):
    """
    On rollback, just clear embeddings since we can't restore old dimensions
    """
    Response = apps.get_model("consultations", "Response")
    Response.objects.update(embedding=None)


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0064_remove_question_multiple_choice_options_and_more"),
    ]

    operations = [
        # First clear existing embeddings
        migrations.RunPython(clear_embeddings, reverse_regenerate),
        # Then alter the field to the new dimensions
        migrations.AlterField(
            model_name="response",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
