# Generated by Django 5.2.4 on 2025-07-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0064_merge_cross_cutting_themes_and_response_free_text"),
        ("consultations", "0064_remove_question_multiple_choice_options_and_more"),
    ]

    operations = []
