# Generated by Django 5.2.4 on 2025-08-06 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0065_alter_response_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossCuttingTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_cutting_themes",
                        to="consultations.consultation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="theme",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.crosscuttingtheme",
            ),
        ),
        migrations.AddConstraint(
            model_name="crosscuttingtheme",
            constraint=models.UniqueConstraint(
                fields=("consultation", "name"), name="unique_cross_cutting_theme"
            ),
        ),
    ]
