# Generated by Django 5.2.4 on 2025-07-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0065_merge_cross_cutting_themes_and_multichoice_refactor"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="crosscuttingtheme",
            name="consultatio_consult_0f4af5_idx",
        ),
        migrations.RemoveIndex(
            model_name="crosscuttingthemeassignment",
            name="consultatio_cross_c_69304c_idx",
        ),
    ]
