# Generated by Django 5.2.5 on 2025-08-17 18:56

from django.db import migrations, models


def back_populate_new_demographics(apps, schema_editor):
    """migrate from demographics (JSON) to new_demographics (m2m)"""
    Respondent = apps.get_model("consultations", "Respondent")
    DemographicOption = apps.get_model("consultations", "DemographicOption")

    for respondent in Respondent.objects.all():
        for name, value in respondent.demographics.items():
            do, _ = DemographicOption.objects.get_or_create(
                consultation=respondent.consultation,
                field_name=name,
                field_value=value,
            )
            respondent.new_demographics.add(do)
        respondent.save()


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0066_crosscuttingtheme_theme_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="respondent",
            name="new_demographics",
            field=models.ManyToManyField(blank=True, to="consultations.demographicoption"),
        ),
        migrations.RunPython(back_populate_new_demographics),
        migrations.RemoveField(
            model_name="respondent",
            name="demographics",
        ),
        migrations.RenameField(
            model_name="respondent",
            old_name="new_demographics",
            new_name="demographics",
        ),
    ]
