# Generated by Django 5.2.5 on 2025-08-17 18:56


from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Critical for long migrations
    dependencies = [
        ("consultations", "0067_responseannotation_new_evidence_rich"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="respondent",
        #     name="new_demographics",
        #     field=models.ManyToManyField(blank=True, to="consultations.demographicoption"),
        # ),
        migrations.RenameField(
            model_name="respondent",
            old_name="demographics",
            new_name="old_demographics",
        ),
        migrations.RenameField(
            model_name="respondent",
            old_name="new_demographics",
            new_name="demographics",
        ),
    ]
