# Generated by Django 5.2.5 on 2025-08-17 18:56


from django.db import migrations, models


def back_populate_new_demographics(apps, schema_editor):
    Respondent = apps.get_model("consultations", "Respondent")
    DemographicOption = apps.get_model("consultations", "DemographicOption")

    processed = 0
    for respondent in Respondent.objects.select_related("consultation").iterator():
        # Skip if already processed (for resume capability)
        if respondent.new_demographics.exists():
            continue

        for name, value in respondent.demographics.items():
            if name and value:
                do, _ = DemographicOption.objects.get_or_create(
                    consultation=respondent.consultation,
                    field_name=name,
                    field_value=value,
                )
                respondent.new_demographics.add(do)

        processed += 1
        if processed % 100 == 0:
            print(f"Processed {processed} respondents")


class Migration(migrations.Migration):
    atomic = False  # Critical for long migrations
    dependencies = [
        ("consultations", "0067_responseannotation_new_evidence_rich"),
    ]

    operations = [
        migrations.AddField(
            model_name="respondent",
            name="new_demographics",
            field=models.ManyToManyField(blank=True, to="consultations.demographicoption"),
        ),
        migrations.RunPython(back_populate_new_demographics),
        migrations.RemoveField(
            model_name="respondent",
            name="demographics",
        ),
        migrations.RenameField(
            model_name="respondent",
            old_name="new_demographics",
            new_name="demographics",
        ),
    ]
