# Generated by Django 5.2.5 on 2025-08-18 08:21

from django.db import migrations, models


def conver_boolean_values(apps, schema_editor):
    DemographicOption = apps.get_model("consultations", "DemographicOption")

    for demographic_option in DemographicOption.objects.all():
        if demographic_option.field_value.lower() == "true":
            demographic_option.field_value = True
        elif demographic_option.field_value.lower() == "false":
            demographic_option.field_value = False
        demographic_option.save()


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0068_remove_respondent_demographics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographicoption",
            name="field_value",
            field=models.JSONField(),
        ),
        migrations.RunPython(conver_boolean_values),
    ]
