# Generated by Django 5.2.5 on 2025-08-18 08:21

from django.db import migrations, models


def convert_json_values(apps, schema_editor):
    DemographicOption = apps.get_model("consultations", "DemographicOption")

    for demographic_option in DemographicOption.objects.all():
        if demographic_option.field_value.lower() == "true":
            demographic_option.new_field_value = True
        elif demographic_option.field_value.lower() == "false":
            demographic_option.new_field_value = False
        else:
            demographic_option.new_field_value = repr(demographic_option.field_value)
        demographic_option.save()


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0068_remove_respondent_demographics_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="respondent",
            old_name="demographics",
            new_name="old_demographics",
        ),
        migrations.RenameField(
            model_name="respondent",
            old_name="new_demographics",
            new_name="demographics",
        ),
        migrations.AddField(
            model_name="demographicoption",
            name="new_field_value",
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(convert_json_values),
        migrations.RemoveField(
            model_name="demographicoption",
            name="field_value",
        ),
        migrations.RenameField(
            model_name="demographicoption",
            old_name="new_field_value",
            new_name="field_value",
        ),
        migrations.AlterField(
            model_name="demographicoption",
            name="field_value",
            field=models.JSONField(),
        ),
    ]
