# Generated by Django 5.2.5 on 2025-08-26 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0070_historicalresponseannotation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="responseannotation",
            name="flagged_by",
            field=models.ManyToManyField(
                blank=True, related_name="flagged_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
