# Generated by Django 5.2.5 on 2025-09-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0071_responseannotation_flagged_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="respondent",
            name="new_demographics",
            field=models.ManyToManyField(blank=True, to="consultations.demographicoption"),
        ),
        migrations.RemoveField(
            model_name="respondent",
            name="demographics",
        ),
        migrations.RenameField(
            model_name="respondent",
            old_name="new_demographics",
            new_name="demographics",
        ),
    ]
