# Generated by Django 5.2.5 on 2025-08-27 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0071_responseannotation_flagged_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="responseannotationtheme",
            name="unique_theme_assignment",
        ),
        migrations.RemoveIndex(
            model_name="responseannotationtheme",
            name="consultatio_respons_cfc7ac_idx",
        ),
        migrations.RemoveIndex(
            model_name="responseannotationtheme",
            name="consultatio_theme_i_16a421_idx",
        ),
        migrations.RemoveField(
            model_name="historicalresponseannotationtheme",
            name="is_original_ai_assignment",
        ),
        migrations.RemoveField(
            model_name="responseannotationtheme",
            name="is_original_ai_assignment",
        ),
        migrations.AlterField(
            model_name="responseannotationtheme",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="responseannotationtheme",
            constraint=models.UniqueConstraint(
                fields=("response_annotation", "theme", "assigned_by"),
                name="unique_theme_assignment",
            ),
        ),
    ]
