# Generated by Django 5.2.5 on 2025-09-03 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0071_responseannotation_flagged_by"),
    ]

    operations = []
