# Generated by Django 5.2.6 on 2025-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0076_candidatetheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="stage",
            field=models.CharField(
                choices=[
                    ("theme_sign_off", "Theme Sign Off"),
                    ("analysis", "Analysis"),
                ],
                default="analysis",
                max_length=32,
            ),
        ),
    ]
