# Generated by Django 5.2.6 on 2025-10-10 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0079_consultation_s3_bucket"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Theme",
            new_name="SelectedTheme",
        ),
        migrations.RenameIndex(
            model_name="selectedtheme",
            new_name="consultatio_questio_dc22ed_idx",
            old_name="consultatio_questio_e016ff_idx",
        ),
    ]
