# Generated by Django 5.2.6 on 2025-10-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0082_candidatetheme_approximate_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatetheme",
            name="approximate_frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
