# Generated by Django 5.2.7 on 2025-10-22 13:58

from django.db import migrations, models


def backfill_code(apps, schema_editor):
    Consultation = apps.get_model("consultations", "Consultation")
    Consultation.objects.filter(code__isnull=True).update(code="missing")


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0085_alter_consultation_code"),
    ]

    operations = [
        migrations.RunPython(backfill_code),
        migrations.AlterModelOptions(
            name="consultation",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="consultation",
            name="unique_consultation_slug",
        ),
        migrations.RemoveConstraint(
            model_name="question",
            name="unique_question_slug",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="s3_bucket",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="question",
            name="slug",
        ),
        migrations.AlterField(
            model_name="consultation",
            name="code",
            field=models.SlugField(max_length=256),
        ),
    ]
