# Generated by Django 5.2.7 on 2025-11-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0085_alter_consultation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="timestamp",
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
