# Generated by Django 5.2.7 on 2025-10-22 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0085_alter_consultation_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultation",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="consultation",
            name="unique_consultation_slug",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="s3_bucket",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="question",
            name="slug",
        ),
    ]
