# Generated by Django 5.2.7 on 2025-11-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0087_alter_consultation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="stage",
            field=models.CharField(
                choices=[
                    ("theme_sign_off", "Theme Sign Off"),
                    ("theme_mapping", "Theme Mapping"),
                    ("analysis", "Analysis"),
                ],
                default="analysis",
                max_length=32,
            ),
        ),
    ]
