# Generated by Django 5.2.8 on 2025-11-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consultations", "0088_alter_consultation_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="stage",
            field=models.CharField(
                choices=[
                    ("theme_sign_off", "Theme Sign Off"),
                    ("theme_mapping", "Theme Mapping"),
                    ("analysis", "Analysis"),
                ],
                default="theme_sign_off",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="theme_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("confirmed", "Confirmed")],
                default="draft",
                max_length=32,
            ),
        ),
    ]
