"""
Django settings for consultation_analyser project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import logging
import os
import sys
from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=False)

env = environ.Env(DEBUG=(bool, False))

SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = env("DEBUG")
ENVIRONMENT = env("ENVIRONMENT")


ALLOWED_HOSTS: list[str] = [os.getenv("DOMAIN_NAME", "0.0.0.0"), "*"]  # nosec

# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.auth",
    "django.contrib.admin",
    "waffle",  # feature flags
    "magic_link",
    "consultation_analyser.authentication",
    "consultation_analyser.consultations",
    "consultation_analyser.support_console",
    "consultation_analyser.error_pages",
    "consultation_analyser.email",
    "compressor",
    "crispy_forms",
    "crispy_forms_gds",
    "django.contrib.humanize",
    "django_rq",
    "simple_history",
    "rest_framework",
    "django_filters",
    "rest_framework_simplejwt",
]


# TODO: steal code from this blog post to add a health check endpoint: https://testdriven.io/blog/deploying-django-to-ecs-with-terraform/#django-health-check

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "waffle.middleware.WaffleMiddleware",
    "consultation_analyser.middleware.LoginRequiredMiddleware404",
    "consultation_analyser.middleware.SupportAppStaffRequiredMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "consultation_analyser.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "APP_DIRS": True,
        "DIRS": [BASE_DIR / "consultation_analyser/lit"],
        "OPTIONS": {
            "environment": "consultation_analyser.jinja2.environment",
            "context_processors": [
                "consultation_analyser.context_processors.app_config",
                "consultation_analyser.context_processors.version",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "DIRS": [BASE_DIR / "consultation_analyser/templates"],
        "OPTIONS": {
            "context_processors": [
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ]
        },
    },
]

WSGI_APPLICATION = "consultation_analyser.wsgi.application"

AUTH_USER_MODEL = "authentication.User"

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4321",
    "https://consult.ai.cabinetoffice.gov.uk",
    "https://consult-dev.ai.cabinetoffice.gov.uk",
]

# Database with Connection Pooling
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

_db_config = env.db()
DATABASES = {
    "default": {
        **_db_config,
        # Use django-db-connection-pool backend for PostgreSQL
        "ENGINE": "dj_db_conn_pool.backends.postgresql",
        # Connection pooling settings
        "POOL_OPTIONS": {
            "INITIAL_CONNS": env.int("DB_POOL_INITIAL_CONNS", default=5),
            "MAX_CONNS": env.int("DB_POOL_MAX_CONNS", default=20),
            "MIN_CONNS": env.int("DB_POOL_MIN_CONNS", default=5),
            "MAX_SHARED_CONNS": env.int("DB_POOL_MAX_SHARED_CONNS", default=10),
            "MAX_OVERFLOW": env.int("DB_POOL_MAX_OVERFLOW", default=10),
            "RECYCLE": env.int("DB_POOL_RECYCLE", default=3600),  # 1 hour
            "PRE_PING": env.bool("DB_POOL_PRE_PING", default=True),
        },
        # Keep existing options
        "OPTIONS": {
            **_db_config.get("OPTIONS", {}),
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

COMPRESS_PRECOMPILERS = (("text/x-scss", "django_libsass.SassCompiler"),)

STATIC_URL = "static/"
STATIC_ROOT = "legacy-frontend/"
STATICFILES_DIRS = [
    ("govuk-assets", BASE_DIR / "node_modules/govuk-frontend/dist/govuk/assets"),
    ("iai-assets", BASE_DIR / "node_modules/i.ai-design-system/dist/"),
]
STATICFILES_FINDERS = [
    "compressor.finders.CompressorFinder",
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "pipeline": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {name}: {message}",
            "style": "{",
        },
        "rq_console": {
            "format": "%(asctime)s %(message)s",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "stdout": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "pipeline",
        },
        "rq_console": {
            "level": "INFO",
            "class": "rq.logutils.ColorizingStreamHandler",
            "stream": sys.stdout,
            "formatter": "rq_console",
            "exclude": ["%(asctime)s"],
        },
    },
    "loggers": {
        "pipeline": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "upload": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "import": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "export": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "dummy_data": {"handlers": ["stdout"], "level": "INFO", "propagate": False},
        "rq.worker": {"handlers": ["rq_console"], "level": "INFO"},
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django URL format
APPEND_SLASH = True

# Feature flags
WAFFLE_SWITCH_DEFAULT = False
WAFFLE_CREATE_MISSING_SWITCHES = True
WAFFLE_LOG_MISSING_SWITCHES = logging.INFO

# Crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "gds"
CRISPY_TEMPLATE_PACK = "gds"

# Email
EMAIL_BACKEND = "django_gov_notify.backends.NotifyEmailBackend"
GOVUK_NOTIFY_API_KEY = env("GOVUK_NOTIFY_API_KEY")
GOVUK_NOTIFY_PLAIN_EMAIL_TEMPLATE_ID = env("GOVUK_NOTIFY_PLAIN_EMAIL_TEMPLATE_ID")

# AWS variables
BATCH_JOB_QUEUE = env("BATCH_JOB_QUEUE", default=None)
BATCH_JOB_DEFINITION = env("BATCH_JOB_DEFINITION", default=None)
AWS_REGION = env("AWS_REGION")
AWS_BUCKET_NAME = env("AWS_BUCKET_NAME")

SQS_QUEUE_URL = env("SQS_QUEUE_URL")
MAPPING_BATCH_JOB_NAME = env("MAPPING_BATCH_JOB_NAME")
MAPPING_BATCH_JOB_QUEUE = env("MAPPING_BATCH_JOB_QUEUE")
MAPPING_BATCH_JOB_DEFINITION = env("MAPPING_BATCH_JOB_DEFINITION")
SIGN_OFF_BATCH_JOB_NAME = env("SIGN_OFF_BATCH_JOB_NAME")
SIGN_OFF_BATCH_JOB_QUEUE = env("SIGN_OFF_BATCH_JOB_QUEUE")
SIGN_OFF_BATCH_JOB_DEFINITION = env("SIGN_OFF_BATCH_JOB_DEFINITION")


# Authentication
LOGIN_URL = "/sign-in/"

# version info
GIT_SHA = env("GIT_SHA", default=None)

# redis
redis_host = env.str("REDIS_HOST", "localhost")
redis_port = env.str("REDIS_PORT", "6379")
redis_url = f"redis://{redis_host}:{redis_port}"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "redis": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": redis_url,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "MAX_ENTRIES": 5000,
        },
    },
}

# rq
RQ_QUEUES = {
    "default": {
        "USE_REDIS_CACHE": "redis",
        "ASYNC": True,
    },
}

# Django debug toolbar
# https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#configure-internal-ips
if DEBUG:
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]
    INSTALLED_APPS += ["debug_toolbar"]
    INTERNAL_IPS = ["127.0.0.1"]

if DEBUG and ("pytest" not in sys.modules and "test" not in sys.argv):
    MIDDLEWARE += ["silk.middleware.SilkyMiddleware"]
    INSTALLED_APPS += ["silk"]

# changing this will require a database migration
EMBEDDING_DIMENSION = 3072

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_RENDERER_CLASSES": (
        "drf_orjson_renderer.renderers.ORJSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=18),
}
