name: build
on:
  push:
    branches:
      - '**'

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      app-name: ${{ steps.export.outputs.app-name }}
      ec2-instance-type: ${{ steps.export.outputs.ec2-instance-type }}
      version: ${{ steps.export.outputs.version }}
      runner-size: ${{ steps.export.outputs.runner-size }}
      docker-build-instance: ${{ steps.export.outputs.docker-build-instance }}
      service: ${{ steps.export.outputs.service }}
      service_matrix: ${{ steps.build-services-matrix.outputs.result }}


    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Load environment
        run: grep -v '^\s*#' .github/.github.env | grep -v '^\s*$' >> $GITHUB_ENV

      - id: export
        run: |
          echo "ec2-instance-type=${EC2_INSTANCE_TYPE}" >> $GITHUB_OUTPUT
          echo "app-name=${APP_NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "runner-size=${RUNNER_SIZE}" >> $GITHUB_OUTPUT
          echo "docker-build-instance=${DOCKER_BUILD_INSTANCE}" >> $GITHUB_OUTPUT
          echo "service=${SERVICE}" >> $GITHUB_OUTPUT

      - id: build-services-matrix
        run: |
          result=$(
            for service in $(echo $SERVICE | tr ',' ' '); do
              tag=$(git log -1 --format="%H" -- ${service}/)
              printf '{"service":"%s","tag":"%s"}\n' "$service" "$tag"
            done | jq -sc '.'
          )
          echo "result=$result" >> $GITHUB_OUTPUT

  start-runner:
    uses: i-dot-ai/i-dot-ai-core-github-actions/.github/workflows/start-runner.yml@main
    needs: set-vars
    permissions: write-all
    with:
        EC2_INSTANCE_TYPE: ${{ needs.set-vars.outputs.ec2-instance-type }}
        RUNNER_SIZE: ${{ needs.set-vars.outputs.runner-size }}
        ENVIRONMENT: ${{ needs.set-vars.outputs.environment }}
        USE_OIDC: true
    secrets:
        AWS_GITHUBRUNNER_USER_ACCESS_KEY: ${{ secrets.AWS_GITHUBRUNNER_USER_ACCESS_KEY }}
        AWS_GITHUBRUNNER_USER_SECRET_ID: ${{ secrets.AWS_GITHUBRUNNER_USER_SECRET_ID }}
        AWS_GITHUBRUNNER_PAT: ${{ secrets.AWS_GITHUBRUNNER_PAT}}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  build-image:
    strategy:
      matrix:
        object: ${{ fromJson(needs.set-vars.outputs.service_matrix) }}
    needs:
      - set-vars
      - start-runner
    permissions: write-all
    uses: i-dot-ai/i-dot-ai-core-github-actions/.github/workflows/build-docker.yml@grajamanoharan/con-264-deploy-consult-container-services-independently
    with:
      APP_NAME: ${{ needs.set-vars.outputs.app-name }}
      RUNNER_LABEL: ${{ needs.start-runner.outputs.label }}
      INFRASTRUCTURE_FOLDER: "infrastructure"
      DOCKER_BUILD_INSTANCE: ${{ needs.set-vars.outputs.docker-build-instance }}
      SERVICE: ${{ matrix.object.service }}
      COMMIT_HASH: ${{ matrix.object.tag }}
      PUSH_IMAGE: false
      USE_OIDC: true
    secrets:
      AWS_GITHUBRUNNER_PAT: ${{ secrets.AWS_GITHUBRUNNER_PAT}}
      AWS_GITHUBRUNNER_PAT_USER: ${{ secrets.AWS_GITHUBRUNNER_PAT_USER }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  stop-runner:
    uses: i-dot-ai/i-dot-ai-core-github-actions/.github/workflows/stop-runner.yml@main
    if: always() && needs.start-runner.outputs.use-persisted == 0
    needs:
      - set-vars
      - start-runner
      - build-image
    permissions: write-all
    with:
      RUNNER_LABEL: ${{ needs.start-runner.outputs.label }}
      EC2_INSTANCE_ID: ${{ needs.start-runner.outputs.ec2-instance-id }}
      USE_OIDC: true
    secrets:
      AWS_GITHUBRUNNER_USER_ACCESS_KEY: ${{ secrets.AWS_GITHUBRUNNER_USER_ACCESS_KEY }}
      AWS_GITHUBRUNNER_USER_SECRET_ID: ${{ secrets.AWS_GITHUBRUNNER_USER_SECRET_ID }}
      AWS_GITHUBRUNNER_PAT: ${{ secrets.AWS_GITHUBRUNNER_PAT}}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
